# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --ignore-scripts
COPY . .
RUN npm run build

FROM node:lts-alpine AS runner
WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev --ignore-scripts
COPY --from=builder /app/dist ./dist

CMD [ "node", "dist/index.js", "--server" ]
